# Python uvod



### Kontrola Toka

Sintaksa:

    if <condition>:
        <code block>
    elif <condition>:
        <code block>
    elif <condition>:
        <code block>
    else:
        <code block>

Where:

+ `<condition>`: uslov koji može biti true ili false.
+ `<code block>`: sekvenca instrukcija.
+ `elif` i `else` su opcioni i nekoliko `elif`-ova za jedan `if` može biti korišćeno, ali samo jedan `else` mora biti na kraju.


In [1]:
temp = 23 # upisati trenutnu temperaturu

if temp < 0:
    print 'Brrrr...'
elif 0 <= temp <= 20:
    print 'Hladno'
elif 21 <= temp <= 25:
    print 'Prijatno'
elif 26 <= temp <= 35:
    print 'Vruce'
else:
    print 'Veoma vruce!'

Prijatno


#### Petlje

**FOR**

Syntax:

    for <reference> in <sequence>:
        <code block>
        continue
        break
    else:
        <code block>

In [ ]:
# Sum 0 to 99
s = 0
for x in range(1, 100):
    s = s + x
print s

#### TODO Ispisati zbir prvih 1000 parnih brojeva

In [ ]:
#put your code here

While
-----

Syntax:

    while <condition>:
        <code block>
        continue
        break
    else:
        <code block>

In [ ]:
# Sum 0 to 99
s = 0
x = 1

while x < 100:
    s = s + x
    x = x + 1
print s

#### TODO Generisati dva slucajna cela broja od 0-100 i ispisati ih ako im je razlika manja od 5. Nakon 50 pokusaja ispisati poruku neuspeha.

### Tipovi podataka

##### Brojevi
-------

+ Integer (*int*): i = 1
+ Floating Point real (*float*): f = 3.14
+ Complex (*complex*): c = 3 + 4j

Primer:

In [2]:
# Converting real to integer
print 'int(3.14) =', int(3.14)

# Converting integer to real
print 'float(5) =', float(5)

# Calculation between integer and real results in real
print '5.0 / 2 + 3 = ', 5.0 / 2 + 3

# Integers in other base
print "int('20', 8) =", int('20', 8) # base 8
print "int('20', 16) =", int('20', 16) # base 16

# Operations with complex numbers
c = 3 + 4j
print 'c =', c
print 'Real Part:', c.real
print 'Imaginary Part:', c.imag
print 'Conjugate:', c.conjugate()

int(3.14) = 3
float(5) = 5.0
5.0 / 2 + 3 =  5.5
int('20', 8) = 16
int('20', 16) = 32
c = (3+4j)
Real Part: 3.0
Imaginary Part: 4.0
Conjugate: (3-4j)


Aritmetičke operacije:

+ Sabiranje (+)
+ Oduzimanje (-)
+ Množenje (*)
+ Deljenje (/): između dva integera rezultat je isti kao i kod integer deljenja. 
+ Integer Deljenje (//): 
+ Modul (%): vreća ostatak pri deljenju.
+ Stepen (**): 
+ Pozitivan (+)
+ Negativan (-)

Logičke Operacije:

+ <
+ >
+ <=
+ >=
+ (==)
+ !=

Bitwise Operacije:

+ Left Shift (<<)
+ Right Shift (>>)
+ And (&)
+ Or (|)
+ Exclusive Or (^)
+ Inversion (~)

Stringovi

Primer

In [3]:
s = 'Camel'

# Concatenation
print 'The ' + s + ' run away!'

# Interpolation
print 'Size of %s => %d' % (s, len(s))

# String processed as a sequence
for ch in s: print ch

# Strings are objects
if s.startswith('C'): print s.upper()

# what will happen? 
print 3 * s
# 3 * s is consistent with s + s + s

The Camel run away!
Size of Camel => 5
C
a
m
e
l
CAMEL
CamelCamelCamel


Python indexi:
====

+ Počinju od nule.
+ Broje se od nazad ako su negativni.
+ Mogu biti definisani kao sekcije, `[start: end + 1: step]`. Ako se ne stavi start, biće računato od nule. Ako nije zadata vrednost end + 1, biće računata veličina objekta. Step je jedan, ako se ne zada nikakva vrednost.

In [4]:
print 'Python'[::-1]
# shows: nohtyP

nohtyP


In [42]:
numbers = range(0,40)
evens = numbers[2::2]

print evens

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]


In [47]:
numbers = range(0,40)
test = numbers[40:0:-2]
test

[39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11, 9, 7, 5, 3, 1]

#### Liste

Syntax:

    list = [a, b, ..., z]

Operacije nad listama:

In [5]:
# a new list: 70s Brit Progs
progs = ['Yes', 'Genesis', 'Pink Floyd', 'ELP']

# processing the entire list
for prog in progs:
    print prog

# Changing the last element
progs[-1] = 'King Crimson'

# Including
progs.append('Camel')

# Removing
progs.remove('Pink Floyd')

# Ordering 
progs.sort()

# Inverting
progs.reverse()

# prints with number order
for i, prog in enumerate(progs):
    print i + 1, '=>', prog

# prints from de second item
print progs[1:]

my_list = ['A', 'B', 'C']
print 'list:', my_list

# The empty list is evaluated as false
while my_list:
    # In queues, the first item is the first to go out
    # pop(0) removes and returns the first item 
    print 'Left', my_list.pop(0), ', remain', len(my_list)

# More items on the list
my_list += ['D', 'E', 'F']
print 'list:', my_list

while my_list:
    # On stacks, the first item is the last to go out
    # pop() removes and retorns the last item
    print 'Left', my_list.pop(), ', remain', len(my_list)

Yes
Genesis
Pink Floyd
ELP
1 => Yes
2 => King Crimson
3 => Genesis
4 => Camel
['King Crimson', 'Genesis', 'Camel']
list: ['A', 'B', 'C']
Left A , remain 2
Left B , remain 1
Left C , remain 0
list: ['D', 'E', 'F']
Left F , remain 2
Left E , remain 1
Left D , remain 0


In [48]:
ls = [True, 0, "Awesome"]
print ls

[1,2,3] < [1,2,4]

[True, 0, 'Awesome']


True

Tuples (Skup)
------

Syntax:

    my_tuple = (a, b, ..., z)

In [6]:
t = ([1, 2], 4)
t[0].append(3)

print t

([1, 2, 3], 4)


#### Set

In [7]:
# Data sets
s1 = set(range(3))
s2 = set(range(10, 7, -1))
s3 = set(range(2, 10, 2))

# Shows the data
print 's1:', s1, '\ns2:', s2, '\ns3:', s3

# Union
s1s2 = s1.union(s2)
print 'Union of s1 and s2:', s1s2

# Difference
print 'Difference with s3:', s1s2.difference(s3)

# Intersectiono
print 'Intersection with s3:', s1s2.intersection(s3)

# Tests if a set includes the other
if s1.issuperset([1, 2]):
    print 's1 includes 1 and 2'

# Tests if there is no common elements
if s1.isdisjoint(s2):
    print 's1 and s2 have no common elements'

s1: set([0, 1, 2]) 
s2: set([8, 9, 10]) 
s3: set([8, 2, 4, 6])
Union of s1 and s2: set([0, 1, 2, 8, 9, 10])
Difference with s3: set([0, 1, 10, 9])
Intersection with s3: set([8, 2])
s1 includes 1 and 2
s1 and s2 have no common elements


### Rečnik

Syntax:
dictionary = {'a': a, 'b': b, ..., 'z': z}


Primeri:
dic = {'name': 'Shirley Manson', 'band': 'Garbage'}


Pristupanje elementima:
print dic['name']


Dodavenja elemenata:
dic['album'] = 'Version 2.0'


Brisanje elementa iz rečnika:
del dic['album']


Pribavljanje svih ključeva, vrednosti i parova ključ, vrednost:
items = dic.items()
keys = dic.keys()
values = dic.values()



In [8]:
# Progs and their albums
progs = {'Yes': ['Close To The Edge', 'Fragile'],
    'Genesis': ['Foxtrot', 'The Nursery Crime'],
    'ELP': ['Brain Salad Surgery']}

# More progs
progs['King Crimson'] = ['Red', 'Discipline']

# items() returns a list of 
# tuples with key and value 
for prog, albums in progs.items():
    print prog, '=>', albums

# If there is 'ELP', removes
if progs.has_key('ELP'):
    del progs['ELP']

Yes => ['Close To The Edge', 'Fragile']
ELP => ['Brain Salad Surgery']
Genesis => ['Foxtrot', 'The Nursery Crime']
King Crimson => ['Red', 'Discipline']


In [9]:
import matplotlib.pyplot as plt #ukljucivanje u rad biblioteka, as predstavlja alias pod kojim se biblioteka koristi u kodu
import numpy as np
%matplotlib inline

### Funkcije

Funkcije u python programskom jeziku počinju sa ključnom reči 'def', zatim sledi naziv funckije sa parametrima i dvotačka ':'. Funkcija može da ima povratnu vrednost.

Kao primer biće implementirana sledeća funkcija od x $x$:

$f(x)= \cos(x) \qquad x <0$

$f(x) = \exp(-x) \qquad x \ge 0$

Implementirajmo $f(x)$ funkciji koja se zove `func`. Funkcija vraca vrednost: $z$.

In [10]:
def func(x = 90):
    if x < 0:
        f = np.cos(x)
    else:
        f = np.exp(-x)
    return f

print func(90)
print func(-90)
print func()

8.19401262399e-40
-0.448073616129
8.19401262399e-40


In [11]:
def func2(x):
    assert(x>0)
    return np.cos(x), np.exp(x)
print func2(90)
a,b = func2(90)
print a
print b
#print func2(-5)

(-0.44807361612917013, 1.2204032943178408e+39)
-0.448073616129
1.22040329432e+39


###TODO 1
Napisati python funkciju za sledeći matematički izraz:

$f(x)=e^{-\alpha x}\cos(x)$

Funkcija prima 'x' i alpha kao ulazne parametre i vraća vrednost funkcije. Funkciju nazovite jedinstveno, a ne 'func'.
Dodati labele za ose.


### Lokalne promenljive

Promenljive definisane unutar funkcije, mogu se koristiti samo unutar te funkcije

In [13]:
def localtest(x):
    a = 3
    b = 5
    return a*x + b
print localtest(4)
# print a  # Greska, a je nepoznato izvan funkcije

var1 = 8
def test3():
    var1 = 4
    print 'Goodmorning, var1 equals', var1
test3()
print 'value of var1 outside test3:', var1

17
Goodmorning, var1 equals 4
value of var1 outside test3: 8


### TODO 2 definisati funkciju za racunanje Fibonacijevog niza

### Vektori i matrice

Numpy and Scipy nude mogućnost za rad sa vekorima i matricama.


In [54]:
import numpy as np

print np.array([1,2,3,4,5,6])
print np.array([1,2,3,4,5,6],'d')
print np.array([1,2,3,4,5,6],'D')

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j])

In [58]:
#kreiranje matrice kao dva vektora

print np.array([[0,1],[1,0]],'d')

#kreiranje nula matrice
print '\n nula matrica \n'
print np.zeros((3,3),'d')

[[ 0.  1.]
 [ 1.  0.]]

 nula matrica 

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [59]:
#linspace lak nacin za pravljenje koordinata

print np.linspace(0,1,11)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [68]:
#primer mnozenja matrica

print np.identity(2)*np.ones((2,2))

print np.dot(np.identity(2),np.ones((2,2)))

[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  1.]
 [ 1.  1.]]


In [69]:
#transponovanje
m = np.array([[1,2],[3,4]])
m.T

array([[1, 3],
       [2, 4]])

In [71]:
#dijagonala
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
#zadatak iz matrica